Problem: I see a lot of inconsistencies in protobuf numbering. This is mainly because of more than one person working on the same feature. Eg. Someone working on the same struct as different person. Both of them added the new field with increasing number. However at the time of submission for both the CLs, we ended up with two fields using the same number. Eg. scenario: http://gkecl/1527944
Next steps: Add it to kokoro so that kokoro runs at rebasing.

Result: (sample failure):
```
➜  compute-class-api git:(5362dd3) go test -v ./api/cloud.google.com/v1
=== RUN   TestProtobufOrderIsIncreasing
=== RUN   TestProtobufOrderIsIncreasing/ComputeClass
=== RUN   TestProtobufOrderIsIncreasing/ComputeClassList
=== RUN   TestProtobufOrderIsIncreasing/ComputeClassSpec
=== RUN   TestProtobufOrderIsIncreasing/AutoscalingPolicy
=== RUN   TestProtobufOrderIsIncreasing/ActiveMigration
=== RUN   TestProtobufOrderIsIncreasing/NodePoolAutoCreation
=== RUN   TestProtobufOrderIsIncreasing/Autopilot
=== RUN   TestProtobufOrderIsIncreasing/NodePoolConfig
=== RUN   TestProtobufOrderIsIncreasing/Gvnic
=== RUN   TestProtobufOrderIsIncreasing/ImageStreaming
=== RUN   TestProtobufOrderIsIncreasing/NodePoolGroup
=== RUN   TestProtobufOrderIsIncreasing/Storage
=== RUN   TestProtobufOrderIsIncreasing/SecondaryBootDisk
=== RUN   TestProtobufOrderIsIncreasing/SpecificReservation
=== RUN   TestProtobufOrderIsIncreasing/ReservationBlock
=== RUN   TestProtobufOrderIsIncreasing/ReservationSubBlock
=== RUN   TestProtobufOrderIsIncreasing/Reservations
    types_test.go:82: field 'Affinity' has protobuf number 1, which is not greater than the previous number 1
=== RUN   TestProtobufOrderIsIncreasing/Priority
=== RUN   TestProtobufOrderIsIncreasing/Placement
=== RUN   TestProtobufOrderIsIncreasing/GPU
=== RUN   TestProtobufOrderIsIncreasing/TPU
=== RUN   TestProtobufOrderIsIncreasing/FlexStart
=== RUN   TestProtobufOrderIsIncreasing/NodeRecyclingConfig
=== RUN   TestProtobufOrderIsIncreasing/NodeSystemConfig
=== RUN   TestProtobufOrderIsIncreasing/LinuxNodeConfig
=== RUN   TestProtobufOrderIsIncreasing/EvictionSoft
=== RUN   TestProtobufOrderIsIncreasing/EvictionSoftGracePeriod
=== RUN   TestProtobufOrderIsIncreasing/EvictionMinimumReclaim
=== RUN   TestProtobufOrderIsIncreasing/KubeletConfig
    types_test.go:82: field 'EvictionSoft' has protobuf number 13, which is not greater than the previous number 13
=== RUN   TestProtobufOrderIsIncreasing/SysctlsConfig
=== RUN   TestProtobufOrderIsIncreasing/HugepagesConfig
=== RUN   TestProtobufOrderIsIncreasing/Location
=== RUN   TestProtobufOrderIsIncreasing/PriorityDefaults
=== RUN   TestProtobufOrderIsIncreasing/TaintConfig
=== RUN   TestProtobufOrderIsIncreasing/Tags
=== RUN   TestProtobufOrderIsIncreasing/ComputeClassStatus
=== RUN   TestProtobufOrderIsIncreasing/HostMaintenancePolicy
--- FAIL: TestProtobufOrderIsIncreasing (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ComputeClass (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ComputeClassList (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ComputeClassSpec (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/AutoscalingPolicy (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ActiveMigration (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/NodePoolAutoCreation (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Autopilot (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/NodePoolConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Gvnic (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ImageStreaming (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/NodePoolGroup (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Storage (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/SecondaryBootDisk (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/SpecificReservation (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ReservationBlock (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ReservationSubBlock (0.00s)
    --- FAIL: TestProtobufOrderIsIncreasing/Reservations (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Priority (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Placement (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/GPU (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/TPU (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/FlexStart (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/NodeRecyclingConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/NodeSystemConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/LinuxNodeConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/EvictionSoft (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/EvictionSoftGracePeriod (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/EvictionMinimumReclaim (0.00s)
    --- FAIL: TestProtobufOrderIsIncreasing/KubeletConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/SysctlsConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/HugepagesConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Location (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/PriorityDefaults (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/TaintConfig (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/Tags (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/ComputeClassStatus (0.00s)
    --- PASS: TestProtobufOrderIsIncreasing/HostMaintenancePolicy (0.00s)
FAIL
FAIL    github.com/googlecloudplatform/compute-class-api/api/cloud.google.com/v1        0.014s
FAIL
```


Change-Id: I4ea4dc52714bcdf0057479c7f1b504f4bd30e6f1